name: zonai_routes
publish_to: none

resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  zonai_application:
    path: ../application
  zonai_ui:
    path: ../ui
  zenrouter: ^2.0.3
  zenrouter_devtools: ^2.0.0
