name: zonai_web
description: Zonai Flutter web application.
publish_to: none

resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  get_it: ^9.2.0
  hive_ce_flutter: ^2.3.4
  path_provider: ^2.1.5
  zonai_application:
    path: packages/application
  zonai_data:
    path: packages/data
  zonai_routes:
    path: packages/routes
  zonai_ui:
    path: packages/ui

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
