part of zonai_db;

/// Tables a [PurgeRecordsRequest] is allowed to touch.
///
/// Derived from the framework's own table list rather than written out, so a
/// new internal table is covered without anyone remembering to add it here —
/// and, more importantly, so an *application* table can never appear in it.
///
/// `_photos` is the one exclusion. Deleting a photo row also deletes the file
/// behind it (`_deletePhotoFile`, reached from the per-row delete path), and a
/// bulk `DELETE` has no per-row step to hang that on. Purging it would orphan
/// every file it removed rows for. `_cleanup_unreferenced_photos` already does
/// that job properly, one row at a time.
final Set<String> _purgeableTables = InternalDbArtifacts.tableNames.difference({
  '_photos',
});

extension _PurgeX on ZonaiDb {
  /// Deletes every row matching [where] as a single statement, returning how
  /// many were removed.
  ///
  /// This is the bulk counterpart to [_delete], and it deliberately skips the
  /// machinery that one runs: no read-back of the matched rows, no per-row
  /// rules dispatch, no sanitization, no `before`/`after` extension callbacks.
  /// That machinery is correct for author tables and unusable for retention —
  /// `_delete` begins by SELECTing every row it is about to remove, with no
  /// limit, and materializing them all. A retention sweep over a few million
  /// rows cannot survive it, which is exactly the state the field reported.
  ///
  /// Skipping row rules is safe here only because of the two gates above it:
  ///
  ///  * [table] must be one of [_purgeableTables] — the framework's own
  ///    tables, whose rules are generated rather than author-supplied, so
  ///    there is no application policy to bypass.
  ///  * [jwt] must be an admin identity. Scheduled crons satisfy this through
  ///    [CronJwt] (`isAdmin: true`), so they need no special-casing; anything
  ///    reaching this without admin is refused the same way a table-rules
  ///    denial would refuse it.
  ///
  /// Both are enforced here, host-side, rather than trusted from the caller:
  /// the request arrives over IPC from a worker process.
  Future<int> _purge({
    required String table,
    required Where where,
    required Jwt? jwt,
  }) async {
    if (jwt?.admin.isAdmin != true) {
      throw const TableAccessDeniedException(table: '', operation: 'purge');
    }

    if (!_purgeableTables.contains(table)) {
      throw TableAccessDeniedException(table: table, operation: 'purge');
    }

    // The same statement `_delete` ends up running -- generated by the
    // operations layer rather than hand-built here, so a change to how a
    // `Where` becomes SQL reaches both paths. What is skipped is everything
    // `_deleteOperation` does *before* this point.
    final operation = await _getOperation(
      DeleteOperationRequest(
        table: table,
        where: where,
        limit: null,
        jwt: jwt,
      ),
    );

    final (error, result) = await _execute((
      operation.query,
      operation.values,
    ));

    if (error != null || result == null) {
      _throwDatabaseError(
        error,
        table: table,
        failure: ([cause]) =>
            RecordDeleteFailedException(table: table, cause: cause),
      );
    }

    logger.verbose(
      'Purged ${result.rowsAffected} rows from $table',
      prefix: _prefix,
    );

    return result.rowsAffected;
  }
}
