name: zonai_server
publish_to: none

resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  path: ^1.9.1
  revali_client: ^2.0.4
  revali_router: ^3.1.0
  scoped_deps:
    path: ../../libs/scoped_deps
  zonai:
    path: ../cli

dev_dependencies:
  revali: ^2.0.9
  revali_client_gen: ^2.0.2
  revali_server: ^2.1.0
