import 'package:raindrop/raindrop.dart' as raindrop;
import 'package:raindrop/raindrop.dart';
import 'package:zonai/src/internal/internal_db_migrations.dart';

/// Applies versioned migrations for framework-managed SQLite tables.
abstract final class InternalDbMigrate {
  /// Embedded SQL migrations generated by raindrop_cli (see [raindrop.yaml]).
  static List<Migration> get migrations => internalDbMigrations;

  /// Runs legacy one-shot upgrades, then pending [migrations].
  static Future<void> apply(Raindrop db) async {
    await _renameLegacyCollectionColumns(db);
    await raindrop.migrate(db, migrations);
  }

  /// Upgrades databases created before internal migrations existed.
  ///
  /// [SqliteInternalTableSync] used a `collection` column name; schemas now use
  /// `table`. Renames are skipped when the old column is absent.
  static Future<void> _renameLegacyCollectionColumns(Raindrop db) async {
    const renames = [
      ('_auth_challenges', 'collection', 'table'),
      ('_rate_limit', 'collection', 'table'),
      ('_photos', 'collection', 'table'),
    ];

    for (final (table, from, to) in renames) {
      if (!await _sqliteTableExists(db, table)) {
        continue;
      }
      if (!await _sqliteColumnExists(db, table, from)) {
        continue;
      }
      await db.execute(
        'ALTER TABLE "$table" RENAME COLUMN "$from" TO "$to"',
      );
    }
  }

  static Future<bool> _sqliteTableExists(Raindrop db, String tableName) async {
    final result = await db.execute(
      "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ? LIMIT 1",
      [tableName],
    );
    return result.rows.isNotEmpty;
  }

  static Future<bool> _sqliteColumnExists(
    Raindrop db,
    String tableName,
    String columnName,
  ) async {
    final result = await db.execute(
      'SELECT 1 FROM pragma_table_info(?) WHERE name = ? LIMIT 1',
      [tableName, columnName],
    );
    return result.rows.isNotEmpty;
  }
}
