#!/usr/bin/env bash
# Refuse a VERSION bump that left the committed generated clients behind.
#
# WHY THIS EXISTS, measured 2026-08-19 during the v0.8.1 release: `zonai gen
# client` stamps the CLI version into every file it writes -- each header says
# "Generated by `zonai gen client` (zonai X.Y.Z)" and the manifest carries
# `generatorVersion` -- and apps/playground commits that output as its golden
# baseline. So editing one line of VERSION invalidates 17 committed files that
# nothing in the release flow regenerates.
#
# It was already caught, by gen_client_golden_test.dart and
# doc_fixture_client_golden_test.dart. The problem was WHEN: those run in
# `Test / unit`, which is reached only after Compile has built five platform
# binaries, so the answer arrived roughly fifteen minutes and one full chain
# after the one-line commit that caused it -- and a new sha means the whole
# chain again. This asks the same question in `static`, in milliseconds, before
# anything is built.
#
# It is deliberately NOT a second copy of the golden check. It compares one
# string and can only catch a version skew; the goldens still own whether the
# generated code is correct. A file whose header says 0.8.1 while its body is
# stale passes here and fails there, which is the right division: this is the
# cheap early-out, not the proof.
#
# To fix a failure, from the repo root:
#
#   sip run version gen                        # VERSION -> lib/gen/version.dart
#   cd apps/playground \
#     && UPDATE_GOLDENS=1 dart test test/gen_client_golden_test.dart \
#     && UPDATE_GOLDENS=1 dart test test/doc_fixture_client_golden_test.dart
#
# The first line is not optional and is the part that is easy to miss:
# apps/zonai/lib/gen/version.dart is gitignored, so a checkout keeps whatever
# the last bootstrap wrote there and regenerating without it bakes the OLD
# version straight back into the goldens.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
version="$(tr -d '[:space:]' < "${ROOT}/VERSION")"

if [[ -z "${version}" ]]; then
  echo "VERSION is empty" >&2
  exit 1
fi

# Globbed rather than listed: a third generated client added later is covered
# without anybody remembering this file. `nullglob` so an empty match is caught
# by the count check below instead of leaving a literal glob in the loop.
shopt -s nullglob
manifests=("${ROOT}"/apps/playground/lib/gen/*/zonai_client_manifest.json)
shopt -u nullglob

# Zero manifests would pass every loop below without checking anything, which is
# the silent-pass shape this repo has been bitten by before.
if [[ "${#manifests[@]}" -eq 0 ]]; then
  echo "no generated client manifests found under apps/playground/lib/gen/" >&2
  echo "This check found nothing to check, which is a failure, not a pass." >&2
  exit 1
fi

failed=0
for manifest in "${manifests[@]}"; do
  rel="${manifest#"${ROOT}/"}"
  stamped="$(sed -n 's/.*"generatorVersion"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "${manifest}" | head -n1)"

  if [[ -z "${stamped}" ]]; then
    echo "${rel}: no generatorVersion field" >&2
    failed=1
  elif [[ "${stamped}" != "${version}" ]]; then
    echo "${rel}: generated by ${stamped}, but VERSION is ${version}" >&2
    failed=1
  else
    echo "  ok: ${rel} (${stamped})"
  fi
done

if [[ "${failed}" -ne 0 ]]; then
  echo "" >&2
  echo "The committed generated clients are stale for VERSION ${version}." >&2
  echo "Regenerate them -- see the header of tool/ci/check_generated_client_version.sh:" >&2
  echo "" >&2
  echo "  sip run version gen" >&2
  echo "  cd apps/playground \\" >&2
  echo "    && UPDATE_GOLDENS=1 dart test test/gen_client_golden_test.dart \\" >&2
  echo "    && UPDATE_GOLDENS=1 dart test test/doc_fixture_client_golden_test.dart" >&2
  exit 1
fi

echo "  ok: every generated client is stamped ${version}"
