#!/usr/bin/env bash
# Package compiled zonai binaries into ONE self-extracting "fat" file that
# dispatches to the right embedded slice for the current OS/arch.
#
# Covers macOS (x64 + arm64) and Linux (x64 + arm64) as a single polyglot
# file: it opens with a `#!/bin/sh` line, which both kernels recognize as a
# script, and the script extracts + execs the matching payload appended
# after it. Windows can't share these bytes -- ELF, Mach-O and PE each
# require their own magic at byte 0 of the file, and a Windows loader will
# never fall back to shebang parsing -- so windows-x64 stays a separate
# zonai.exe (see package_release_assets.sh).
#
# The two macOS slices are embedded SEPARATELY, not merged into a real
# lipo(1) universal binary: `dart compile exe` appends its AOT snapshot
# after the formal Mach-O segments, and lipo's slice concatenation does not
# preserve that trailer -- the resulting universal binary launches but dies
# with "<arg> is not an AOT snapshot, it cannot be run with 'dartaotruntime'"
# (confirmed directly: `lipo -create` on two real release binaries, run with
# no wrapper involved, reproduces the same failure). This script picks the
# macOS slice by `uname -m` instead, same as it already does for Linux.
#
# Each zonai payload is xz-compressed at package time (measured ~76%
# smaller on the real v0.5.1 binaries: ~145MiB -> ~34MiB). Decompression on
# first run uses a tiny vendored decoder for the matching platform
# (tool/ci/vendor/unxz/, ~70-330 KiB each, statically linked -- see its
# README) embedded in the fat file right alongside the payload, so the
# *user* never needs `xz` installed. The CI machine building the release
# still needs `xz` to produce the compressed payloads in the first place.
#
# Usage: package_fat_binary.sh <artifacts-dir> [output-dir]
#
# Expects the same artifact layout as package_release_assets.sh:
#   <artifacts-dir>/zonai-linux-x64/zonai
#   <artifacts-dir>/zonai-linux-arm64/zonai
#   <artifacts-dir>/zonai-macos-arm64/zonai
#   <artifacts-dir>/zonai-macos-x64/zonai
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
vendor_dir="${repo_root}/tool/ci/vendor/unxz"

artifacts_dir="${1:?artifacts directory required}"
output_dir="${2:-release-assets}"
mkdir -p "${output_dir}"

linux_x64="${artifacts_dir}/zonai-linux-x64/zonai"
linux_arm64="${artifacts_dir}/zonai-linux-arm64/zonai"
macos_arm64="${artifacts_dir}/zonai-macos-arm64/zonai"
macos_x64="${artifacts_dir}/zonai-macos-x64/zonai"

for f in "$linux_x64" "$linux_arm64" "$macos_arm64" "$macos_x64"; do
  if [[ ! -f "${f}" ]]; then
    echo "missing release binary: ${f}" >&2
    exit 1
  fi
done

dec_linux_x64="${vendor_dir}/linux-x64"
dec_linux_arm64="${vendor_dir}/linux-arm64"
dec_macos_arm64="${vendor_dir}/macos-arm64"
dec_macos_x64="${vendor_dir}/macos-x64"

for f in "$dec_linux_x64" "$dec_linux_arm64" "$dec_macos_arm64" "$dec_macos_x64"; do
  if [[ ! -f "${f}" ]]; then
    echo "missing vendored decoder: ${f} (see tool/ci/vendor/unxz/README.md)" >&2
    exit 1
  fi
done

if ! command -v xz >/dev/null 2>&1; then
  echo "xz not found -- required to compress the embedded payloads" >&2
  exit 1
fi

work_dir="$(mktemp -d)"
trap 'rm -rf "${work_dir}"' EXIT

xz_linux_x64="${work_dir}/zonai-linux-x64.xz"
xz_linux_arm64="${work_dir}/zonai-linux-arm64.xz"
xz_macos_arm64="${work_dir}/zonai-macos-arm64.xz"
xz_macos_x64="${work_dir}/zonai-macos-x64.xz"

xz -9 -c "${linux_x64}" > "${xz_linux_x64}"
xz -9 -c "${linux_arm64}" > "${xz_linux_arm64}"
xz -9 -c "${macos_arm64}" > "${xz_macos_arm64}"
xz -9 -c "${macos_x64}" > "${xz_macos_x64}"

version="$(tr -d '[:space:]' < "${repo_root}/VERSION")"

len_dec_linux_x64="$(wc -c < "${dec_linux_x64}" | tr -d ' ')"
len_dec_linux_arm64="$(wc -c < "${dec_linux_arm64}" | tr -d ' ')"
len_dec_macos_arm64="$(wc -c < "${dec_macos_arm64}" | tr -d ' ')"
len_dec_macos_x64="$(wc -c < "${dec_macos_x64}" | tr -d ' ')"

len_xz_linux_x64="$(wc -c < "${xz_linux_x64}" | tr -d ' ')"
len_xz_linux_arm64="$(wc -c < "${xz_linux_arm64}" | tr -d ' ')"
len_xz_macos_arm64="$(wc -c < "${xz_macos_arm64}" | tr -d ' ')"

header="${work_dir}/header.sh"
cat > "${header}" <<HEADER
#!/bin/sh
# zonai fat binary launcher -- generated by tool/ci/package_fat_binary.sh.
# Do not hand-edit. Payload layout after the marker line, 8 slices:
#   decoder(linux-x64), decoder(linux-arm64), decoder(macos-arm64),
#   decoder(macos-x64), zonai(linux-x64).xz, zonai(linux-arm64).xz,
#   zonai(macos-arm64).xz, zonai(macos-x64).xz (to EOF).
# Each decoder is a tiny static xz decompressor (see
# tool/ci/vendor/unxz/README.md) -- no system \`xz\` is required to run this.
set -e

ZONAI_VERSION="${version}"
LEN_DEC_LINUX_X64=${len_dec_linux_x64}
LEN_DEC_LINUX_ARM64=${len_dec_linux_arm64}
LEN_DEC_MACOS_ARM64=${len_dec_macos_arm64}
LEN_DEC_MACOS_X64=${len_dec_macos_x64}
LEN_XZ_LINUX_X64=${len_xz_linux_x64}
LEN_XZ_LINUX_ARM64=${len_xz_linux_arm64}
LEN_XZ_MACOS_ARM64=${len_xz_macos_arm64}

os="\$(uname -s)"
arch="\$(uname -m)"

self="\$0"
case "\${self}" in
  /*) ;;
  *) self="\$(pwd)/\${self}" ;;
esac

header_lines="\$(awk '/^__ZONAI_PAYLOAD__\$/{print NR; exit}' "\${self}")"
if [ -z "\${header_lines}" ]; then
  echo "zonai: corrupt fat binary (payload marker not found)" >&2
  exit 1
fi
payload_start="\$(head -n "\${header_lines}" "\${self}" | wc -c | tr -d ' ')"

dec_base=\$((payload_start))
xz_base=\$((payload_start + LEN_DEC_LINUX_X64 + LEN_DEC_LINUX_ARM64 + LEN_DEC_MACOS_ARM64 + LEN_DEC_MACOS_X64))

case "\${os}" in
  Linux)
    case "\${arch}" in
      x86_64)
        dec_skip="\${dec_base}"; dec_len="\${LEN_DEC_LINUX_X64}"
        pl_skip="\${xz_base}"; pl_len="\${LEN_XZ_LINUX_X64}"
        ;;
      aarch64|arm64)
        dec_skip=\$((dec_base + LEN_DEC_LINUX_X64)); dec_len="\${LEN_DEC_LINUX_ARM64}"
        pl_skip=\$((xz_base + LEN_XZ_LINUX_X64)); pl_len="\${LEN_XZ_LINUX_ARM64}"
        ;;
      *) echo "zonai: unsupported Linux architecture: \${arch}" >&2; exit 1 ;;
    esac
    ;;
  Darwin)
    case "\${arch}" in
      arm64)
        dec_skip=\$((dec_base + LEN_DEC_LINUX_X64 + LEN_DEC_LINUX_ARM64)); dec_len="\${LEN_DEC_MACOS_ARM64}"
        pl_skip=\$((xz_base + LEN_XZ_LINUX_X64 + LEN_XZ_LINUX_ARM64)); pl_len="\${LEN_XZ_MACOS_ARM64}"
        ;;
      x86_64)
        dec_skip=\$((dec_base + LEN_DEC_LINUX_X64 + LEN_DEC_LINUX_ARM64 + LEN_DEC_MACOS_ARM64)); dec_len="\${LEN_DEC_MACOS_X64}"
        pl_skip=\$((xz_base + LEN_XZ_LINUX_X64 + LEN_XZ_LINUX_ARM64 + LEN_XZ_MACOS_ARM64)); pl_len=""
        ;;
      *) echo "zonai: unsupported macOS architecture: \${arch}" >&2; exit 1 ;;
    esac
    ;;
  *)
    echo "zonai: unsupported OS: \${os} -- use zonai.exe on Windows" >&2
    exit 1
    ;;
esac

cache_dir="\${ZONAI_FAT_CACHE:-\${XDG_CACHE_HOME:-\${HOME}/.cache}/zonai/fat}"
mkdir -p "\${cache_dir}" 2>/dev/null || { cache_dir="\${TMPDIR:-/tmp}/zonai-fat-cache"; mkdir -p "\${cache_dir}"; }

dest="\${cache_dir}/zonai-\${ZONAI_VERSION}-\${os}-\${arch}"

if [ ! -x "\${dest}" ]; then
  dec_tmp="\${dest}.\$\$.dec.tmp"
  tail -c "+\$((dec_skip + 1))" "\${self}" | head -c "\${dec_len}" > "\${dec_tmp}"
  chmod +x "\${dec_tmp}"

  tmp="\${dest}.\$\$.tmp"
  if [ -n "\${pl_len}" ]; then
    tail -c "+\$((pl_skip + 1))" "\${self}" | head -c "\${pl_len}" | "\${dec_tmp}" > "\${tmp}"
  else
    tail -c "+\$((pl_skip + 1))" "\${self}" | "\${dec_tmp}" > "\${tmp}"
  fi
  rm -f "\${dec_tmp}"
  chmod +x "\${tmp}"
  mv "\${tmp}" "\${dest}"
fi

exec "\${dest}" "\$@"
exit 1
__ZONAI_PAYLOAD__
HEADER

out="${output_dir}/zonai"
cat "${header}" \
  "${dec_linux_x64}" "${dec_linux_arm64}" "${dec_macos_arm64}" "${dec_macos_x64}" \
  "${xz_linux_x64}" "${xz_linux_arm64}" "${xz_macos_arm64}" "${xz_macos_x64}" \
  > "${out}"
chmod +x "${out}"

echo "Packaged fat binary: ${out} ($(wc -c < "${out}" | tr -d ' ') bytes)"
echo "  decoders:    $((len_dec_linux_x64 + len_dec_linux_arm64 + len_dec_macos_arm64 + len_dec_macos_x64)) bytes total"
echo "  linux-x64:   ${len_xz_linux_x64} bytes (compressed)"
echo "  linux-arm64: ${len_xz_linux_arm64} bytes (compressed)"
echo "  macos-arm64: ${len_xz_macos_arm64} bytes (compressed)"
echo "  macos-x64:   $(wc -c < "${xz_macos_x64}" | tr -d ' ') bytes (compressed)"
