#!/usr/bin/env bash
# Updates pubspec_overrides.yaml to pull revali packages from GitHub instead of local paths.
#
# Usage: use_revali_git_overrides.sh [target-dir]
#
# [target-dir] is relative to the repo root and defaults to the root itself,
# whose overrides cover every workspace member. Pass a directory for a project
# that resolves on its own -- e2e/ fixtures are not workspace members, so the
# root's overrides never reach them, and they would silently resolve the
# revali family from pub.dev while everything else in the run is pinned here.
#
# Environment:
#   REVALI_GIT_URL  — repository URL (default: https://github.com/mrgnhnt96/revali.git)
#   REVALI_GIT_REF  — branch, tag, or commit (default: main)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
target_dir="${1:-.}"
PUBSPEC_OVERRIDES="$(cd "${ROOT}/${target_dir}" && pwd)/pubspec_overrides.yaml"
REVALI_GIT_URL="${REVALI_GIT_URL:-https://github.com/mrgnhnt96/revali.git}"
REVALI_GIT_REF="${REVALI_GIT_REF:-main}"

write_git_override() {
  local package="$1"
  local path="$2"
  cat <<EOF
  ${package}:
    git:
      url: ${REVALI_GIT_URL}
      ref: ${REVALI_GIT_REF}
      path: ${path}
EOF
}

{
  cat <<EOF
# GENERATED BY tool/ci/use_revali_git_overrides.sh -- CI-ONLY. DELETE THIS FILE
# WHEN YOU'RE DONE, THEN RUN \`dart pub get\`.
#
# This pins the revali family to ${REVALI_GIT_REF} (${REVALI_GIT_URL}) instead
# of whatever pubspec.yaml would otherwise resolve. It's gitignored, so
# \`git status\` will never flag a leftover copy -- if you ran this locally
# (e.g. reproducing a CI-only failure) and forget to delete it, every
# \`dart test\`/\`dart pub get\` you run afterward stays silently pinned to
# this ref, which can drift from what everyone else is running without any
# visible signal that it happened.
dependency_overrides:
EOF
  write_git_override revali_router revali_router/revali_router
  write_git_override revali packages/revali
  write_git_override revali_client constructs/revali_client/revali_client
  write_git_override revali_client_gen constructs/revali_client/revali_client_gen
  write_git_override revali_docker constructs/revali_docker
  write_git_override revali_swagger constructs/revali_swagger/revali_swagger
  write_git_override revali_swagger_annotations constructs/revali_swagger/revali_swagger_annotations
  write_git_override revali_construct packages/revali_construct
  write_git_override revali_core packages/revali_core
  write_git_override revali_annotations packages/revali_annotations
} > "${PUBSPEC_OVERRIDES}"

echo "Wrote ${PUBSPEC_OVERRIDES} (url: ${REVALI_GIT_URL}, ref: ${REVALI_GIT_REF})"
