name: zonai_playground
publish_to: none

resolution: workspace

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  meta: ^1.17.0

dev_dependencies:
  test: ^1.26.0
  zonai:
    path: ../zonai
  zonai_schema:
    path: ../../libs/zonai_schema
