name: zonai_ui
publish_to: none

resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  file_picker: ^10.3.10
  flex_color_scheme: ^8.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_inappwebview: ^6.1.5
  flutter_svg: ^2.2.3
  formz: ^0.8.0
  get_it: ^9.2.0
  nested: ^1.0.0
  pointer_interceptor: ^0.10.1+2
  provider: ^6.1.5
  select_when: ^1.0.1+1
  url_launcher: ^6.3.2
  web: ^1.1.1
  zenrouter: ^2.0.3
  zonai_application:
    path: ../application
  zonai_routes:
    path: ../routes

dev_dependencies:
  flutter_gen: ^5.12.0

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true

  integrations:
    flutter_svg: true
