name: zonai_cli
publish_to: none

resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  file: ">=6.0.0 <8.0.0"
  yaml: ^3.1.0
  raindrop_cli:
    path: ../../libs/raindrop/packages/raindrop_cli
  scoped_deps: ^0.1.0+2
  zonai_logger:
    path: ../../libs/zonai_logger
  watcher: ^1.2.1
  async: ^2.13.1

dev_dependencies:
  test: ^1.26.0

executables:
  zonai:
